/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Link2HeadingPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  parentHeading: "",
  headingLevel: "auto",
  missingParentBehavior: "top"
};
var Link2HeadingSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Parent heading").setDesc("New headings will be inserted under this heading. Leave empty to insert at top of file.").addText(
      (text) => text.setPlaceholder("e.g., Notes, Ideas, etc.").setValue(this.plugin.settings.parentHeading).onChange(async (value) => {
        this.plugin.settings.parentHeading = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Heading level").setDesc("The heading level for newly created headings.").addDropdown(
      (dropdown) => dropdown.addOption("auto", "One level below parent").addOption("h1", "H1").addOption("h2", "H2").addOption("h3", "H3").addOption("h4", "H4").addOption("h5", "H5").addOption("h6", "H6").setValue(this.plugin.settings.headingLevel).onChange(async (value) => {
        this.plugin.settings.headingLevel = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("If parent heading doesn't exist").setDesc("What to do with the new heading when the configured parent heading is not found.").addDropdown(
      (dropdown) => dropdown.addOption("top", "Insert at top of file").addOption("create", "Create parent heading").addOption("none", "Do nothing").setValue(this.plugin.settings.missingParentBehavior).onChange(async (value) => {
        this.plugin.settings.missingParentBehavior = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// utils.ts
function getLineAfterFrontmatter(editor) {
  if (editor.getLine(0) !== "---") return 0;
  for (let i = 1; i < editor.lineCount(); i++) {
    if (editor.getLine(i) === "---") return i + 1;
  }
  return 0;
}
function calculateHeadingLevel(headingLevelSetting, parentLevel) {
  if (headingLevelSetting !== "auto") {
    const level = parseInt(headingLevelSetting.replace("h", ""));
    return Math.min(Math.max(level, 1), 6);
  }
  if (parentLevel !== null) return Math.min(parentLevel + 1, 6);
  return 3;
}
function findInsertionPoint(editor, existingHeadings, settings) {
  const topLine = getLineAfterFrontmatter(editor);
  if (!settings.parentHeading) {
    return { insertionPoint: { line: topLine, ch: 0 }, parentLevel: null, needsParentCreation: false };
  }
  const parentHeading = existingHeadings == null ? void 0 : existingHeadings.find(
    (h) => h.heading.toLowerCase() === settings.parentHeading.toLowerCase()
  );
  if (parentHeading) {
    return {
      insertionPoint: { line: parentHeading.position.end.line + 1, ch: 0 },
      parentLevel: parentHeading.level,
      needsParentCreation: false
    };
  }
  switch (settings.missingParentBehavior) {
    case "top":
      return { insertionPoint: { line: topLine, ch: 0 }, parentLevel: null, needsParentCreation: false };
    case "create":
      return { insertionPoint: { line: topLine, ch: 0 }, parentLevel: null, needsParentCreation: true };
    case "none":
      return null;
  }
}
function buildHeadingText(headingText, level, parentHeading, parentLevel, needsParentCreation, prevLineContent) {
  let text = "";
  let linesAdded = 0;
  if (prevLineContent && prevLineContent !== "---") {
    text += "\n";
    linesAdded++;
  }
  if (needsParentCreation && parentHeading) {
    text += `${"#".repeat(parentLevel)} ${parentHeading}

`;
    linesAdded += 2;
  }
  text += `${"#".repeat(level)} ${headingText}

`;
  linesAdded += 2;
  return { text, linesAdded };
}
function parseLinkWithHeading(linktext, sourcePath, resolveFile) {
  if (!linktext.includes("#")) return null;
  const [filePart, headingPart] = linktext.split("#");
  if (!headingPart) return null;
  const resolvedPath = resolveFile(filePart || "", sourcePath);
  return {
    file: resolvedPath || filePart || "",
    heading: decodeURIComponent(headingPart)
  };
}

// main.ts
var Link2HeadingPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.pendingHeading = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new Link2HeadingSettingTab(this.app, this));
    const originalOpenLinkText = this.app.workspace.openLinkText.bind(this.app.workspace);
    this.app.workspace.openLinkText = async (linktext, sourcePath, newLeaf, openViewState) => {
      const parsed = parseLinkWithHeading(linktext, sourcePath, (linkPath, srcPath) => {
        var _a;
        return ((_a = this.app.metadataCache.getFirstLinkpathDest(linkPath, srcPath)) == null ? void 0 : _a.path) || null;
      });
      if (parsed) this.pendingHeading = parsed;
      return originalOpenLinkText(linktext, sourcePath, newLeaf, openViewState);
    };
    this.register(() => {
      this.app.workspace.openLinkText = originalOpenLinkText;
    });
    this.registerEvent(
      this.app.workspace.on("file-open", async (file) => {
        if (!file || !this.pendingHeading) return;
        await new Promise((resolve) => setTimeout(resolve, 50));
        const isExpectedFile = this.pendingHeading.file === file.path || file.path.endsWith(this.pendingHeading.file + ".md") || this.pendingHeading.file === file.basename;
        if (!isExpectedFile) {
          this.pendingHeading = null;
          return;
        }
        const headingText = this.pendingHeading.heading;
        this.pendingHeading = null;
        const view = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
        if ((view == null ? void 0 : view.file) === file) {
          await this.handleHeadingNavigation(file, headingText, view);
        }
      })
    );
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async handleHeadingNavigation(file, headingText, view) {
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache || (0, import_obsidian2.resolveSubpath)(cache, "#" + headingText)) return;
    const editor = view.editor;
    if (editor) await this.createHeading(headingText, editor, cache.headings);
  }
  async createHeading(headingText, editor, existingHeadings) {
    const insertionResult = findInsertionPoint(editor, existingHeadings, this.settings);
    if (!insertionResult) return;
    const { insertionPoint, parentLevel, needsParentCreation } = insertionResult;
    const level = calculateHeadingLevel(this.settings.headingLevel, parentLevel);
    const parentLevelNum = this.settings.headingLevel === "auto" ? 2 : Math.max(1, level - 1);
    const prevLineContent = insertionPoint.line > 0 ? editor.getLine(insertionPoint.line - 1) : "";
    const { text, linesAdded } = buildHeadingText(
      headingText,
      level,
      this.settings.parentHeading || null,
      parentLevelNum,
      needsParentCreation,
      prevLineContent
    );
    editor.replaceRange(text, insertionPoint);
    editor.setCursor({ line: insertionPoint.line + linesAdded - 1, ch: 0 });
  }
};
